### ISSUE TITLE
cacert error on OS X

### ISSUE THREAD

**Issue by lucasgonze** [soda480/rest3client#36]
Summary: github3api fails on OS X as a result of rest3client hard-coding the path to the certificate file to a location specific to Linux.

Platform:
```
$ uname -a
Darwin M1-Air-2086 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 x86_64

```

Code:
```
from github3api import GitHubAPI
client = GitHubAPI(bearer_token="fnord")
```

Shell:
```
$ python dependabot-alerts.py 
cabundle "/etc/ssl/certs/ca-certificates.crt" is not accessible
```

Cause:
https://github.com/soda480/rest3client/blob/4dd69b5f9010f31266231cca7b3a9dd5381efde7/src/main/python/rest3client/restclient.py#L38
```
    cabundle = '/etc/ssl/certs/ca-certificates.crt'
        self.cabundle = RESTclient.get_cabundle(kwargs.get('cabundle'))
```

**Comment by soda480** [comment]
hi @lucasgonze ...
you can override the CA certificate default file location in two ways:
1) setting the `REQUESTS_CA_BUNDLE` environment variable or
2) passing it in via the GitHubAPI constructor:
```
client = GitHubAPI(bearer_token="fnord", cabundle='/location/to/your/cabundle')
```

please advise if this helps or if you prefer a different behavior.

**Comment by lucasgonze** [comment]
Thanks. I'm able to use these workarounds to get my own usecase to work.

Is this documented anywhere?

**Comment by soda480** [comment]
@lucasgonze 
CABundle override options have been documented [here](https://github.com/soda480/rest3client#certificate-authority-ca-bundle). Thanks.
